// Action names
export let SET_ROLLER_DATA = "SET_ROLLER_DATA";
export let SET_SLOT_ELEMENT =  "SET_SLOT_ELEMENT";
export let WAIT_TO_START_SPIN = "WAIT_TO_START_SPIN";
export let SET_WAIT_TO_SPIN = "SET_WAIT_TO_SPIN";
export let START_SPIN = "START_SPIN";
export let SET_SPINNING = "SET_SPINNING";
export let SPINNING_STARTED = "SPINNING_STARTED";
export let SET_STOP_SPINNING = "SET_STOP_SPINNING";
export let STOP_SPINNING = "STOP_SPINNING";
export let SPINNING_STOPPED = "SPINNING_STOPPED";